#!/bin/bash
#This file contains hacks made to use gnu utils easily

extract () {
    if [ -f $1 ] ; then
      dir=${1%.*}    
      case $1 in
        *.tar.bz2)   tar xjvf $1     ;;
        *.tar.gz)    tar xzvf $1     ;;
        *.bz2)       bunzip2 $1     ;;
        *.rar)       unrar e $1     ;;
        *.gz)        gunzip $1      ;;
        *.tar)       tar xvf $1      ;;
        *.tbz2)      tar xjvf $1     ;;
        *.tgz)       tar xzvf $1     ;;
        *.zip)       unzip $1       ;;
        *.jar)       unzip $1 -d $dir ;;
        *.Z)         uncompress $1  ;;
        *.7z)        7z x $1        ;;
        *)     echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

#search for process and kill the process by prompting it first
function killit() {
	local ps=`which ps`
	local command=`"$ps" -ef`
	echo $command
}
